# Generated by Django 4.2.4 on 2024-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
