# Generated by Django 4.2.4 on 2024-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_pricelist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='currency',
            field=models.CharField(choices=[('Indian Rupee', 'Indian Rupee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='item_rate_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Each Item', 'Each Item')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='round_off',
            field=models.CharField(choices=[('Never Mind', 'Never Mind'), ('Nearest Whole Number', 'Nearest Whole Number'), ('0.99', '0.99'), ('0.50', '0.50'), ('0.49', '0.49')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Purchase', 'Purchase')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='custom_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='standard_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricelisttransactionhistory',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricelisttransactionhistory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
