# Generated by Django 4.2.4 on 2024-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_alter_pricelist_currency_alter_pricelist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
