# Generated by Django 4.2.4 on 2024-01-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_pricelist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='percentage_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
