# Generated by Django 4.2.4 on 2024-01-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0008_remove_zohomodules_reconciliation'),
        ('Company_Staff', '0005_alter_pricelist_percentage_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.pricelist')),
            ],
        ),
    ]
