# Generated by Django 4.2.4 on 2024-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_pricelistcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='price_list_attachment/'),
        ),
    ]
