# Generated by Django 4.2.4 on 2024-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_pricelist_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='standard_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
