# Generated by Django 4.2.4 on 2024-02-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0008_alter_pricelistitem_custom_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistcomment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
